/**
 * PosalPro MVP2 - Proposals Queue API Route
 * Returns approval queue items for workflow management
 */

import { authOptions } from '@/lib/auth';
import { getServerSession } from 'next-auth';
import { NextRequest, NextResponse } from 'next/server';

export async function GET(request: NextRequest) {
  try {
    const session = await getServerSession(authOptions);

    if (!session?.user?.id) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // Mock approval queue data
    const queueItems = [
      {
        id: 'queue-001',
        workflowId: 'wf-001',
        proposalId: 'proposal-001',
        proposalName: 'Enterprise Cloud Migration Solution',
        client: 'TechCorp Industries',
        currentStage: 'Technical Review',
        stageType: 'Technical',
        assignee: 'System Administrator',
        priority: 'Critical',
        urgency: 'Today',
        complexity: 8,
        estimatedDuration: 4,
        deadline: new Date('2024-12-22T17:00:00Z'),
        slaRemaining: 18,
        status: 'In Review',
        riskLevel: 'High',
        dependencies: ['security-assessment', 'compliance-check'],
        collaborators: ['John Smith', 'Sarah Johnson'],
        lastActivity: new Date('2024-12-19T14:30:00Z'),
        proposalValue: 2500000,
        isOverdue: false,
        isCriticalPath: true,
        escalationLevel: 1,
        reviewCycles: 2,
        requiredActions: ['Complete technical specifications', 'Security compliance review'],
        attachments: 5,
      },
      {
        id: 'queue-002',
        workflowId: 'wf-002',
        proposalId: 'proposal-002',
        proposalName: 'Digital Transformation Platform',
        client: 'Global Manufacturing Corp',
        currentStage: 'Legal Review',
        stageType: 'Legal',
        assignee: 'Legal Team',
        priority: 'High',
        urgency: 'This Week',
        complexity: 6,
        estimatedDuration: 6,
        deadline: new Date('2024-12-25T17:00:00Z'),
        slaRemaining: 72,
        status: 'Pending',
        riskLevel: 'Medium',
        dependencies: ['contract-terms'],
        collaborators: ['Mike Wilson', 'Lisa Chen'],
        lastActivity: new Date('2024-12-18T10:15:00Z'),
        proposalValue: 1800000,
        isOverdue: false,
        isCriticalPath: false,
        escalationLevel: 0,
        reviewCycles: 1,
        requiredActions: ['Contract terms review', 'Liability assessment'],
        attachments: 3,
      },
      {
        id: 'queue-003',
        workflowId: 'wf-003',
        proposalId: 'proposal-003',
        proposalName: 'AI-Powered Analytics Suite',
        client: 'DataTech Solutions',
        currentStage: 'Executive Approval',
        stageType: 'Executive',
        assignee: 'Executive Team',
        priority: 'Medium',
        urgency: 'Next Week',
        complexity: 7,
        estimatedDuration: 2,
        deadline: new Date('2024-12-30T17:00:00Z'),
        slaRemaining: 120,
        status: 'Needs Info',
        riskLevel: 'Low',
        dependencies: ['budget-approval'],
        collaborators: ['David Brown', 'Emma Davis'],
        lastActivity: new Date('2024-12-17T16:45:00Z'),
        proposalValue: 950000,
        isOverdue: false,
        isCriticalPath: false,
        escalationLevel: 0,
        reviewCycles: 1,
        requiredActions: ['Budget confirmation', 'Resource allocation'],
        attachments: 2,
      },
      {
        id: 'queue-004',
        workflowId: 'wf-004',
        proposalId: 'proposal-004',
        proposalName: 'Cybersecurity Infrastructure Upgrade',
        client: 'SecureBank Financial',
        currentStage: 'Security Assessment',
        stageType: 'Security',
        assignee: 'Security Team',
        priority: 'Critical',
        urgency: 'Immediate',
        complexity: 9,
        estimatedDuration: 8,
        deadline: new Date('2024-12-20T17:00:00Z'),
        slaRemaining: 6,
        status: 'Escalated',
        riskLevel: 'Critical',
        dependencies: ['penetration-testing', 'compliance-audit'],
        collaborators: ['Alex Rodriguez', 'Jennifer Kim'],
        lastActivity: new Date('2024-12-19T09:00:00Z'),
        proposalValue: 3200000,
        isOverdue: true,
        isCriticalPath: true,
        escalationLevel: 2,
        reviewCycles: 3,
        requiredActions: [
          'Complete security audit',
          'Risk mitigation plan',
          'Compliance verification',
        ],
        attachments: 8,
      },
      {
        id: 'queue-005',
        workflowId: 'wf-005',
        proposalId: 'proposal-005',
        proposalName: 'Supply Chain Optimization System',
        client: 'LogisticsPro Inc',
        currentStage: 'Finance Review',
        stageType: 'Finance',
        assignee: 'Finance Team',
        priority: 'High',
        urgency: 'Today',
        complexity: 5,
        estimatedDuration: 3,
        deadline: new Date('2024-12-23T17:00:00Z'),
        slaRemaining: 24,
        status: 'In Review',
        riskLevel: 'Medium',
        dependencies: ['cost-analysis'],
        collaborators: ['Robert Taylor', 'Maria Garcia'],
        lastActivity: new Date('2024-12-19T11:20:00Z'),
        proposalValue: 1400000,
        isOverdue: false,
        isCriticalPath: true,
        escalationLevel: 0,
        reviewCycles: 1,
        requiredActions: ['Financial impact analysis', 'ROI calculation'],
        attachments: 4,
      },
      {
        id: 'queue-006',
        workflowId: 'wf-006',
        proposalId: 'proposal-006',
        proposalName: 'Healthcare Data Management Platform',
        client: 'MedTech Healthcare',
        currentStage: 'Compliance Review',
        stageType: 'Compliance',
        assignee: 'Compliance Team',
        priority: 'High',
        urgency: 'This Week',
        complexity: 8,
        estimatedDuration: 5,
        deadline: new Date('2024-12-27T17:00:00Z'),
        slaRemaining: 96,
        status: 'Blocked',
        riskLevel: 'High',
        dependencies: ['hipaa-assessment', 'data-privacy-review'],
        collaborators: ['Kevin Lee', 'Amanda White'],
        lastActivity: new Date('2024-12-16T14:30:00Z'),
        proposalValue: 2100000,
        isOverdue: false,
        isCriticalPath: false,
        escalationLevel: 1,
        reviewCycles: 2,
        requiredActions: ['HIPAA compliance verification', 'Data privacy impact assessment'],
        attachments: 6,
      },
    ];

    return NextResponse.json(queueItems);
  } catch (error) {
    console.error('Proposals Queue API error:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
